3week/mini_routes/config/routes.rb
MiniRoutes::Application.routes.draw do
  resources :urls, :users, :sessions
  
  # get "sessions/new"
  # get "sessions/destroy"
  # get "users/new"
  # get "users/show"
  # get "users/create"
  

  root to: 'urls#index' 

  get '/small/', to: 'urls#small', as: :small

  get '/signup' => 'users#new'
  delete '/signout', to: 'sessions#destroy', via: :delete
  get'/signin' => 'sessions#new'

  # get '/urls/:id/preview', to: 'urls#preview', as: :preview

  # get '/urls/:id', to: 'uls#final', as: :final


end

3week/mini_routes/app/models/url.rb
# == Schema Information
#
# Table name: urls
#
#  id            :integer          not null
#  link          :string(255)
#  random_string :string(255)      primary key
#  count         :integer
#  created_at    :datetime
#  updated_at    :datetime
#

class Url < ActiveRecord::Base
 	self.primary_key = "random_string"  
 	# validates: :link, :presence => true, :link, :uniqueness => true
end

3week/mini_routes/app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  name            :string(255)
#  email           :string(255)
#  created_at      :datetime
#  updated_at      :datetime
#  password_digest :string(255)
#

class User < ActiveRecord::Base

	before_create {|user| user.email.downcase!}
	before_create :create_remember_token
	
	before_save :create_remember_token
  
 	has_secure_password

 	validates :name, presence: true, length: { maximum: 50 }
 	validates :email, presence: true, uniqueness: { case_sensitve: false}
 	validates :password, presence: true, lengt: { minimum: 6 }, confirmation: true
 	validates :password_confirmation, presence: true


 	private

    	def create_remember_token
        	self.remember_token = SecureRandom.urlsafe_base64
    	end 
end

3week/mini_routes/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
include SessionsHelper
  protect_from_forgery with: :exception
end

3week/mini_routes/app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
end

3week/mini_routes/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new
		render :new
	end

	def destroy
		sign_out
		redirect_to root_url
	end 

	def create
	signin_params = params.require(:session).permit(:email, :password)
	user=User.find_by_email(signin_params[:email].downcase)
		if user && user.authenticate(signin_params[:password])
	    	# Sign the user in and redirect to the user's show page.
	    	sign_in user
	    	redirect_to user
		else
	    	# Create an error message and re-render the signin form.
	    	flash.now[:error]='Invalid email/password combination'
	    	render :new
		end
	end

end

3week/mini_routes/app/controllers/urls_controller.rb
class UrlsController < ApplicationController
   before_filter :signed_in_user, only: [:create, :new, :edit]
	def index
		@url = Url.new
	end

	# def new
  		
	# end

	def create 
		new_url = params.require(:url).permit(:link)
		new_url["random_string"] = SecureRandom.urlsafe_base64(14)
		new_url["count"] = 0
		# url = Url.create(new_url)
		url = Url.create_with(random_string: new_url["random_string"], count: new_url["count"]).find_or_create_by(link: new_url['link'])
		redirect_to url_path(url)
	end

	def show
		id = params[:id]
		@url = Url.find(id)
		@url.increment!(:count, by = 1)
	end

	def small
		random_string = params[:random_string] 
		@url = Url.find_by(random_string: random_string)
		@url.increment!(:count, by = 1)
		#binding.pry
	end

	def site(url) 
		u = URI.parse(url.link)
			if(!u.scheme)
    			url.link = "http://#{url.link}"
    		end
	end

	def edit
		id = params[:id]
    	url = Url.find(id)
    	updated_info = params.require(:url).permit(:random_string)
    	#binding.pry
    		if Url.find_by(random_string: params[:url][:random_string])
				flash[:warning]="That short URL already exists! Please enter a different short URL:"
			else
				url.update_attributes(updated_info)
			end
    	redirect_to action: :show
	end

	helper_method :site

end

3week/mini_routes/app/controllers/users_controller.rb
class UsersController < ApplicationController
 def new
	    @user = User.new()
	end

	def show
	    @user = User.find(params[:id])
	end

	def create
		new_user= params.require(:user).permit(:name, :email, :password, :password_confirmation)
		@user= User.new(new_user)
	    if @user.save
	        flash[:success] = "Welcome to the Tiny URL World!"
	        sign_in @user
	        redirect_to @user
	    else
	        render'new'
	    end
	end

	def update
	    @user = User.find(params[:id])
	    @user.update_attributes(params[:user])
	    render :show
	end
end

3week/mini_routes/app/helpers/categories_helper.rb
module CategoriesHelper
end

3week/mini_routes/app/helpers/sessions_helper.rb
module SessionsHelper
  def sign_in(user)
  	
	cookies.permanent[:remember_token] = user.remember_token
	# current_user is avilable in controllers and views!
	# This is an is an assignment, which we must define - see below
	# note that next line is a call to setter 'def current_user=(user)' below
	current_user = user
  end

	def signed_in?
		!current_user.nil?
	end

	# Authorization: signed_in_user is called in a before_filter
	# callback in each controller, see books/ingredients/recipe controllers
	# Ensures access to create/edit functions on if signed in.
	def signed_in_user
	unless signed_in?
	    # If not signed in, save current location in session object
	    # to be able to redirect after successful sign in.
	    session[:return_to] = request.url
	    # prompt sign in page
	    redirect_to signin_url, notice: "Please sign in."
	end
	end

	# signs out user by deleting @current_user and session cookie
	def sign_out
	@current_user = nil
	cookies.delete(:remember_token)
	end

	# Getter and setter for @current_user
	def current_user=(user)
	@current_user = user
	end

	# if current_user doesn't exist, check session cookie for user session
	# If exists, get the user record that belongs to that session.
	def current_user
	@current_user ||= User.find_by_remember_token(cookies[:remember_token])
	end
end

3week/mini_routes/app/helpers/urls_helper.rb
module UrlsHelper
end

3week/mini_routes/app/helpers/users_helper.rb
module UsersHelper
end

3week/mini_routes/app/views/layouts/_header.html.erb
<header>
  <div class="navbar-inner">
    <div class="container">
      <nav class="navbar navbar-default" role="navigation">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
	<ul class="nav pull-right">
        <% #binding.pry %>
        <% if signed_in? %>
          <li><%= link_to "My profile", current_user %></li>
          <li>
            <%= link_to "Sign out", signout_path, method: "delete" %>
          </li>
        <% else %>
          <li><%= link_to "Sign up", signup_path %></li>
          <li><%= link_to "Sign in", signin_path %></li>
        <% end %>
      </ul>
  		</div>
      </nav>
    </div>
  </div>
</header>

3week/mini_routes/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MiniRoutes</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" type ="text/css" href="/assets/bootstrap.min.css">
  <link rel="stylesheet" type ="text/css" href="/assets/style.css">
  <link href='http://fonts.googleapis.com/css?family=Gloria+Hallelujah' rel='stylesheet' type='text/css'>
</head>
<body>
<%= render 'layouts/header' %>
<div id="left"></div>
<div id="right"></div>
<div id="top"></div>
<div id="bottom"></div>
<%= yield %>

</body>
</html>

3week/mini_routes/app/views/users/_form_new.html.erb
 <%= form_for (@user) do |f| %>
  	<%= f.label :name %><%= f.text_field :name %>
  	<%= f.label :email %><%= f.text_field :email %>
  	<%= f.label :password %><%= f.text_field :password %>
  	<%= f.label :password_confirmation %><%= f.text_field :password_confirmation %>
  	<%= f.submit "Create my account", class: "btn btn-default" %>
<% end %>

3week/mini_routes/app/views/users/new.html.erb
<h1>Sign up</h1>

<div class="row">
    <div class="span6 offset3">

   		<%= render partial: "form_new" %>

    </div>
</div>

3week/mini_routes/app/views/users/show.html.erb
<div class="row">
    <aside class="span4">
        <ul>
        	<li>Name: <%= @user.name%></li>
        	<li>Email: <%= @user.email %></li>
        	<li>Password: <%= @user.password %></li>
        </ul>
    </aside>
</div>